### ISSUE TITLE
comparison to video-extensions

### ISSUE THREAD

**Issue by jonschlinkert** [KennethSweezy/video-extensions-list#1]
How does this library differ from https://www.npmjs.com/package/video-extensions?

**Comment by sweezyio** [comment]
@jonschlinkert The [video-extensions](https://www.npmjs.com/package/video-extensions) library only includes 33 of the most common video file extensions. Meanwhile, this library ([video-extensions-list](https://www.npmjs.com/package/video-extensions-list)) has many more with 488 different video extensions.
